version: "3.9"

services:
  backend:
    image: oussamadhraief/tickets-backend:latest  # Use Docker Hub image
    ports:
      - "5000:5000"

  frontend:
    image: oussamadhraief/tickets-frontend:latest  # Use Docker Hub image
    ports:
      - "3000:3000"
    depends_on:
      - backend
