name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push frontend
        run: |
          docker build -t oussamadhraief/tickets-frontend:latest ./frontend
          docker push oussamadhraief/tickets-frontend:latest

      - name: Build and push backend
        run: |
          docker build -t oussamadhraief/tickets-backend:latest ./backend
          docker push oussamadhraief/tickets-backend:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/frontend-deployment.yaml

